spring:
  config:
    import: env.properties
  profiles:
    active: ${ACTIVE}

api:
  version: /api/v1

server:
  port: ${PORT}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
  access:
    leave:
      minutes: ${JWT_ACCESS_LEAVE_MINUTES}
  refresh:
    leave:
      days: ${JWT_REFRESH_LEAVE_DAYS}
  authorization:
    user:
      field: username

---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:secrets.properties[.properties]
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: ${DEV_JPA_DIALECT}

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: ${DEV_JPA_DIALECT}
